sonar.projectKey=stratpoint_sdet-cicd-training
sonar.organization=stratpoint

# Sources
sonar.sources=playwright-python,playwright-typescript
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/playwright-report/**

# Python
sonar.python.version=3.11

# Test paths (excluded from main analysis)
sonar.tests=playwright-python/tests,playwright-typescript/tests
sonar.test.inclusions=**/test_*.py,**/*.spec.ts
